### ISSUE TITLE
Chummer5a is GPL

### ISSUE THREAD

**Issue by apathy-dude** [hgehlhausen/chummer-js#1]
Just noticed this is released under MIT license but if you look at the chummer5a project it's licensed under GPLv3 so there might be issues if you want to use stuff from the original project such as the xml files they use for all the data.

You could of course always dual license if you do take a copy of their xml files.

**Comment by hgehlhausen** [comment]
Thanks for the heads up! 
I hadn't realized the legal issue - still trying to find time between work and play to get further on this... Since their data files are xml based, I probably couldn't use them easily in their current form anyway.
Main end-product objective is to have an open-source, web-based program that can do much of the complicated, behind-the-scenes calculations of Shadowrun 5e. I don't even have a firm grasp on the  game system myself, so I'm not expecting this to happen overnight.
